### ISSUE TITLE
complete clinical stage description for currently described topographies

### ISSUE THREAD

**Issue by djogopatrao** [djogopatrao/tnm_ontology#3]
not all topographies (as of f0a499bec222d87477eded833c632717f098f3e2) are implemented. for those, only rules stating advanced stages (CS III or IV) were described

create rules for all other stages, including substages such as breast CS IIIb

do not implement the metastasis location modifier for M1.

**Comment by calebern** [comment]
Fixed in commit d59186b1235986c4a1a7bee096a105e3a56798d9.

**Comment by henriquetomaz** [comment]
Fixed in commits:
e30279e371a3b5505c0349c251c08eb2b8803393
bfbf7a775149c7bce3f0f9e1ba4b10519f3dc2b5
